### PR TITLE
Add a tutorial / demo for using GAN for image parametrization

### PR DESCRIPTION
**Pull request by Animadversio**
I'm back a year later. I think some has suggested me to provide a tutorial of how to use the GAN parameterization and here is one. 

I tried to create a notebook in the same format as the others and added a thumbnail for readme. 
If you need, I could provide you the source Illustrator file for the thumbnail for you to unify the format. 

BTW you may want to unify the image source at the end of the day, currently, some are hosted in my repo. 

strawberry_3pix_crop
strawberry_4FFT_crop
strawberry_1GAN_crop
strawberry_2GAN_crop

### CODE REVIEW

**Comment by Animadversio** [comment]
Kindly reminding you of this pull request! @greentfrapp 
If you like you could review the new tutorial and merge with your repo

**Comment by Animadversio** [comment]
Hi @greentfrapp kindly reminding you of this pull request!

**Comment by greentfrapp** [comment]
Hey @Animadversio thanks so much for your contribution! (and kudos to your perseverance!) Loving this and merging it to dev right now (I'll make a change to the image source in the README before merging to master)

**Comment by greentfrapp** [comment]
Also just wanted to say sorry for the super delayed reply, I have no excuses, it was just pure procrastination :(

**Pull request merged**
